pipeline {
    agent any

    stages {
        stage ("use dir") {
            steps {
                dir("CYB535")
                {
                    bat "mvn test"
                    //echo "hello Im in Java"
                }

                
            }
        }
    }
}
